### ISSUE TITLE
Can't open or create a new notebook in Spyder from custom-launcher on Mac OSX and linux

### ISSUE THREAD

**Issue by andfoy** [spyder-ide/spyder-notebook#106]
@tvashtar commented on [Mon Aug 07 2017](https://github.com/spyder-ide/spyder/issues/4911)

## Description

**What steps will reproduce the problem?**

1. pip install spyder-notebook 
2. Open Spyder
3. Try to Open or create a New Notebook

**What is the expected output? What do you see instead?**

I expected to get a notebook, but I just get an error message, on Mac OSX running Sierra. Note I do have jupyter installed (version 1.0.0), but it seems to be looking for something else?

**Please provide any additional information below**

  File "/Users/conor/anaconda/envs/P3/lib/python3.6/site-packages/spyder_notebook/notebookplugin.py", line 314, in create_new_client
    server_info = nbopen(filename)
  File "/Users/conor/anaconda/envs/P3/lib/python3.6/site-packages/spyder_notebook/utils/nbopen.py", line 75, in nbopen
    proc = subprocess.Popen(command, creationflags=creation_flag)
  File "/Users/conor/anaconda/envs/P3/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/Users/conor/anaconda/envs/P3/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'jupyter'

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.11.2 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  5.4.1 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
@dalthviz, it seems we need to check that Jupyter directory exists before trying to open a notebook.

I think there's some code in the IPython console that does this.

**Comment by dalthviz** [comment]
@tvashtar can you run `jupyter notebook` in a terminal?

**Comment by tvashtar** [comment]
@dalthviz Yep, works no problem, I use it every day.

**Comment by tvashtar** [comment]
Ok I did a little digging and my case is probably a bit more unusual so you can close if you like. I launch Spyder using a bash script inside a barebones MacOs app (so that I can launch it from the dock). This seems to be what is causing the issue. If I launch Spyder from the command line or the Anaconda Launcher spyder-notebook works fine. If I launch it using the app, the notebook tab is blank and opening a notebook throws the error above.

**Comment by juejung** [comment]
The same thing happens under Ubuntu 17.04. Starting Spyder from command line opens the notebook tab correctly and everything works. Starting Spyder from a custom-launcher using (/home/username/anaconda3/bin/spyder) leaves the notebook tab blank. Then a right-click - New Notebook results in the same error message as reported above.

**Comment by LynnHo** [comment]
Has this problem been solved now? I met this in Ubuntu16.04 with custom-launcher and no problem starting in terminal.

**Comment by dalthviz** [comment]
Hi @LynnHo this is not yet resolved. Also, if you manage to find new info to solve this please post it here, we would be really grateful :)

**Comment by dalthviz** [comment]
@LynnHo @juejung could you try editing your custom-launcher to follow something like this:

[Desktop Entry]
Name=Spyder
Comment=Spyder
Exec=sh -c "export PATH=$PATH:**/path/to/anaconda/bin** && echo $PATH && spyder"
Icon=**/path/to/spyder/imag**
Terminal=false
Type=Application

You will need to change the image path and the Anaconda bin directory (or the directory where you have installed the executables for `spyder` and the `jupyter notebook`) path in the custom-launcher following the estructure above. I tested this with Ubuntu 16.04.

**Comment by LynnHo** [comment]
@dalthviz Problem solved on ubuntu 16.04! Many thanks！

**Comment by ccordoba12** [comment]
@dalthviz, this is not a Spyder problem, so I think we should close it.

**Comment by dalthviz** [comment]
@tvashtar maybe the structure of the custom-luncher for Ubuntu that is provided above could help you to make the bash script to launch Spyder from the dock in MacOS with the plugin. If you manage to make it work please let us know :)

**Comment by juejung** [comment]
In spyder.desktop stored In .local/share/applications
this line worked for me on Ubuntu 16.04:

Exec=sh -c "export PATH=$PATH:/path/to/anaconda/bin && echo $PATH && /path/to/anaconda/bin/spyder"

Using the suggested:
Exec=sh -c "export PATH=$PATH:/path/to/anaconda/bin && echo $PATH && spyder"
would start an older version of spyder that was on my system but not the anaconda one.

Thank you for this solution.
