### ISSUE TITLE
spyder-notebook not working on Macbook

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-notebook#142]
@uniele commented on [Wed Feb 07 2018](https://github.com/spyder-ide/spyder/issues/6398)

## Description

**What steps will reproduce the problem?**

1. Install the plugin by "conda install spyder-notebook -c spyder-ide"
2. Spyder shows up but notebook button doesn't. 

**What is the expected output? What do you see instead?**

![image](https://user-images.githubusercontent.com/13804769/35902726-a78540a0-0c1f-11e8-93aa-cb1b1a2e01a3.png)

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.3
* Qt Versions: 5.10.0, PyQt5 5.10 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

---

@BjornFJohansson commented on [Wed Feb 07 2018](https://github.com/spyder-ide/spyder/issues/6398#issuecomment-363679508)

might have have this problem as well, I think that the spyder-notebook started complaining when I installed jupyter extensions. Not sure if that make sense.

---

@BjornFJohansson commented on [Wed Feb 07 2018](https://github.com/spyder-ide/spyder/issues/6398#issuecomment-363680566)

removed spyder-notebook with:
`conda remove spyder-notebook`
and now spyder starts again.

---

@ccordoba12 commented on [Wed Feb 07 2018](https://github.com/spyder-ide/spyder/issues/6398#issuecomment-363892091)

Thanks for reporting. Moving this to the right repo.

**Comment by ccordoba12** [comment]
> Qt Versions: 5.10.0, PyQt5 5.10 on Darwin

@uniele, this is not the default PyQt package in Anaconda. Please install spyder-notebook in a clean conda env, using only Anaconda packages and report back again.

**Comment by uniele** [comment]
Thank you!

**Comment by jsmm** [comment]
This is being reported repeatedly. I will add that it doesn't work on a Mac even in its own newly created environment with `conda create --name spyder spyder-notebook`.

**Comment by ccordoba12** [comment]
@jsmm, what's the error you're getting? Or do simply get a blank plugin, as @uniele reported?

**Comment by jsmm** [comment]
@ccordoba12, 

The tab for notebooks appears in Spyder, and so does `+` to create an new file of such type. But ipynb files are not rendered in Spyder. I attach an image.

![screenshot_55](https://user-images.githubusercontent.com/2811090/36477814-dd779eae-1702-11e8-90a6-a49b31dccd83.jpg)

**Comment by cupdike** [comment]
Seeing same thing as jsmm.  Here's what I see in the console when I go to open a new notebook:

```
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
js: Uncaught TypeError: Cannot set property 'className' of null
js: Uncaught ReferenceError: Invalid left-hand side in assignment
```

Setup was via:
```
conda create -n SpyderNotebooks python=3.6.4 anaconda
source activate SpyderNotebooks
conda install spyder
conda install spyder-notebook -c spyder-ide
conda update jupyter_core jupyter_client
```

**Comment by uniele** [comment]
got the same problem.
![image](https://user-images.githubusercontent.com/13804769/37454730-ac69b9cc-287e-11e8-8e27-f19f3a8de178.png)

Spyder was install by anaconda pkg, and spyder-notebook was install by 
`conda install spyder-notebook -c spyder-ide`

As shown above, notebook was completely blank.

Thanks very much for your helping! @ccordoba12

**Comment by jsmm** [comment]
The problem has been solved after the last upgrade, as far as I am concerned. Spyder can be upgraded to the latest version  both via conda and pip.

**Comment by uniele** [comment]
@jsmm Ok, thank you! I reinstalled and double checked, still not looking good.

Details
* Spyder version: 3.2.8 
* Python version: 3.6.3
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating system: Darwin 17.4.0

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)
```

**Comment by ccordoba12** [comment]
@uniele, could you update spyder-notebook with

    conda install -c spyder-ide spyder-notebook

That could fix this problem.

**Comment by ccordoba12** [comment]
@uniele, I found the solution to this problem. It's a bug with Qt, the graphical library used by Spyder.

Once Anaconda update Qt to its 5.9 version (which should happen soon) this problem will be fixed.

**Comment by ccordoba12** [comment]
Until then, you can downgrade the Jupyter notebook package to its 5.2 version by opening Terminal.app and running there

    conda install notebook=5.2

**Comment by uniele** [comment]
@ccordoba12 Sorry, I just saw this, and done that immediately. 

Thank you for you help very much sir. Worked like a charm.

![image](https://user-images.githubusercontent.com/13804769/37750670-9db76caa-2dd1-11e8-8754-7c8121e6fbba.png)

Appreciated, again.
