### ISSUE TITLE
Error Installing on mac

### ISSUE THREAD

**Issue by eminaz** [spyder-ide/spyder-notebook#151]
## Description of your problem

**What steps will reproduce the problem?**

1. conda install spyder-notebook -c spyder-ide

**What is the expected output? What do you see instead?**
Expect to install, but ran into an error:
"CondaHTTPError: HTTP 400 BAD REQUEST for url <https://conda.anaconda.org/spyder-ide/osx-64/spyder-notebook-0.1.2-py36_0.tar.bz2>"

**Please provide any additional information below (stack trace, screenshots, a gif, etc)**

## Versions and main components

* Spyder Version:Spyder 3.2.6 
* Python Version: 3.6.4
* Qt Version:
* PyQt Version:
* Jupyter Notebook Version: 5.4.0
* Operating system: macOS High Sierra 10.13.5

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Please try again. This looks like an error connection that should be fixed now.

**Comment by eminaz** [comment]
@ccordoba12 Tried again for 3 times just now, still see that error.

**Comment by jitseniesen** [comment]
I can't reproduce this. @eminaz Are you still having this problem?

**Comment by ccordoba12** [comment]
@eminaz, please update conda and try again.

**Comment by jitseniesen** [comment]
This is all about version 0.1 of the plugin, we never managed to reproduce it and we have just released version 0.3, so I am closing this issue. If anybody encounters the same problem with version 0.3, please open a new issue so that we can get to the bottom of it.
